// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9szBFaM6217gQaIF1kz_BGnofT-m3N8',
    appId: '1:6708326527:web:17c43a9c3ebd73388b8f4a',
    messagingSenderId: '6708326527',
    projectId: 'denge-69da6',
    authDomain: 'denge-69da6.firebaseapp.com',
    storageBucket: 'denge-69da6.appspot.com',
    measurementId: 'G-DC28ZWWZ2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWtmPWn0xekh6QVtTPKr4w88hwWrWFBPY',
    appId: '1:6708326527:android:e305b5cdabfe3eac8b8f4a',
    messagingSenderId: '6708326527',
    projectId: 'denge-69da6',
    storageBucket: 'denge-69da6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl__xClkULoIRTbxJe3bESDviF1Bo6u8g',
    appId: '1:6708326527:ios:bbc191814e65c11e8b8f4a',
    messagingSenderId: '6708326527',
    projectId: 'denge-69da6',
    storageBucket: 'denge-69da6.appspot.com',
    iosClientId: '6708326527-ksf85s6ueagg5joaabj0fttjfqhurvgg.apps.googleusercontent.com',
    iosBundleId: 'com.berkayozdemir.denge',
  );
}
